name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-versions: [12, 14, 16]
        operating-systems: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-systems }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions}}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
